### ISSUE TITLE
More words!

### ISSUE THREAD

**Issue by sabasm** [haowen737/react-typewriter-hook#1]
Hi!,
first than anything, THANKYOU!
second, i found out a little change so it doesnt matter how long the magic ocean words count is
`useEffect(
      () => {
        intervalRef.current = setInterval(() => {
          index = index > 2 ? 0 : ++index;
`
:)

**Comment by haowen737** [comment]
Hey @sabasm ,
Thanks for the advice, I can see it is a little enhance for example on CodeSandbox. I'll think about it when putting an example directory in this Repo.

**Comment by sabasm** [comment]
Thank you!

**Comment by haowen737** [comment]
A user-friendly example has been deployed to show [how _react-typewriter-hook_ works](https://haowen737.github.io/react-typewriter-hook/)!
